In [1]:
import pandas as pd
import numpy as np

In [2]:
#Import Data

In [3]:
data = pd.read_csv("/Users/ismaelcisse/Downloads/measurements.csv")

In [4]:
data

distance consume  speed temp_inside  temp_outside specials gas_type  AC  \
0         28       5     26        21,5            12      NaN      E10   0   
1         12     4,2     30        21,5            13      NaN      E10   0   
2       11,2     5,5     38        21,5            15      NaN      E10   0   
3       12,9     3,9     36        21,5            14      NaN      E10   0   
4       18,5     4,5     46        21,5            15      NaN      E10   0   
..       ...     ...    ...         ...           ...      ...      ...  ..   
383       16     3,7     39        24,5            18      NaN     SP98   0   
384     16,1     4,3     38          25            31       AC     SP98   1   
385       16     3,8     45          25            19      NaN     SP98   0   
386     15,4     4,6     42          25            31       AC     SP98   1   
387     14,7       5     25          25            30       AC     SP98   1   

     rain  sun refill liters refill gas  
0       0    0            45        E10  
1       0    0           NaN        NaN  
2       0    0           NaN        NaN  
3       0    0           NaN        NaN  
4       0    0           NaN        NaN  
..    ...  ...           ...        ...  
383     0    0           NaN        NaN  
384     0    0           NaN        NaN  
385     0    0           NaN        NaN  
386     0    0           NaN        NaN  
387     0    0           NaN        NaN  

[388 rows x 12 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   distance       388 non-null    object
 1   consume        388 non-null    object
 2   speed          388 non-null    int64 
 3   temp_inside    376 non-null    object
 4   temp_outside   388 non-null    int64 
 5   specials       93 non-null     object
 6   gas_type       388 non-null    object
 7   AC             388 non-null    int64 
 8   rain           388 non-null    int64 
 9   sun            388 non-null    int64 
 10  refill liters  13 non-null     object
 11  refill gas     13 non-null     object
dtypes: int64(5), object(7)
memory usage: 36.5+ KB


In [43]:
data.describe()

speed  temp_outside          AC        rain         sun
count  388.000000    388.000000  388.000000  388.000000  388.000000
mean    41.927835     11.358247    0.077320    0.123711    0.082474
std     13.598524      6.991542    0.267443    0.329677    0.275441
min     14.000000     -5.000000    0.000000    0.000000    0.000000
25%     32.750000      7.000000    0.000000    0.000000    0.000000
50%     40.500000     10.000000    0.000000    0.000000    0.000000
75%     50.000000     16.000000    0.000000    0.000000    0.000000
max     90.000000     31.000000    1.000000    1.000000    1.000000

In [12]:
data["temp_inside"].unique()

array(['21,5', '22,5', '20', nan, '21', '20,5', '23', '23,5', '25', '24',
       '22', '19', '24,5', '25,5'], dtype=object)

In [18]:
data["temp_inside"].isna().sum()

12

In [20]:
data["specials"].unique()

array([nan, 'AC rain', 'AC', 'rain', 'snow', 'AC snow',
       'half rain half sun', 'sun', 'AC sun', 'sun ac', 'ac', 'AC Sun',
       'ac rain'], dtype=object)

In [22]:
data["temp_outside"].unique()

array([12, 13, 15, 14, 10, 11,  6,  4,  9,  0,  5,  3,  8,  1,  2,  7, -3,
       17, 18, -5, 16, 19, 21, 20, 25, 23, 27, 24, 26, 22, 30, 31, 28])

In [44]:
data["refill liters"].unique()

array(['45', nan, '37.6', '37.7', '38', '38.3', '10', '39', '41', '37',
       '37.2'], dtype=object)

In [45]:
# Change type
#Column : distance, consume, temp_inside, refill liters, refill gas

#1. Replace « , » by « . »

In [40]:
data["distance"] = data["distance"].str.replace(",", ".")
data["consume"] = data["consume"].str.replace(",", ".")
data["temp_inside"] = data["temp_inside"].str.replace(",", ".")
data["refill liters"] = data["refill liters"].str.replace(",", ".")
data["refill gas"] = data["refill gas"].str.replace(",", ".")

In [42]:
data["temp_inside"].unique()

array(['21.5', '22.5', '20', nan, '21', '20.5', '23', '23.5', '25', '24',
       '22', '19', '24.5', '25.5'], dtype=object)

In [59]:
# 2. Convert from object to float

In [57]:
columntoconvert = ['distance','consume','temp_inside','refill liters']

In [56]:
data["refill gas"].unique()

array(['E10', nan, 'SP98'], dtype=object)

In [58]:
for column in columntoconvert:
    if data[column].dtype == 'object':
        data[column] = data[column].astype(float)

In [61]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   distance       388 non-null    float64
 1   consume        388 non-null    float64
 2   speed          388 non-null    int64  
 3   temp_inside    376 non-null    float64
 4   temp_outside   388 non-null    int64  
 5   specials       93 non-null     object 
 6   gas_type       388 non-null    object 
 7   AC             388 non-null    int64  
 8   rain           388 non-null    int64  
 9   sun            388 non-null    int64  
 10  refill liters  13 non-null     float64
 11  refill gas     13 non-null     object 
dtypes: float64(4), int64(5), object(3)
memory usage: 36.5+ KB


In [73]:
data["specials"].unique()

array([nan, 'AC Rain', 'AC', 'rain', 'snow', 'AC snow',
       'half rain half sun', 'sun', 'AC Sun'], dtype=object)

In [85]:
#data["specials"] = data['specials'].replace(['ac'], 'AC')
#data["specials"] = data['specials'].replace(['sun ac','AC sun'], 'AC Sun')
#data["specials"] = data['specials'].replace(['ac rain', 'AC rain'], 'AC Rain')

In [74]:
data

distance  consume  speed  temp_inside  temp_outside specials gas_type  \
0        28.0      5.0     26         21.5            12      NaN      E10   
1        12.0      4.2     30         21.5            13      NaN      E10   
2        11.2      5.5     38         21.5            15      NaN      E10   
3        12.9      3.9     36         21.5            14      NaN      E10   
4        18.5      4.5     46         21.5            15      NaN      E10   
..        ...      ...    ...          ...           ...      ...      ...   
383      16.0      3.7     39         24.5            18      NaN     SP98   
384      16.1      4.3     38         25.0            31       AC     SP98   
385      16.0      3.8     45         25.0            19      NaN     SP98   
386      15.4      4.6     42         25.0            31       AC     SP98   
387      14.7      5.0     25         25.0            30       AC     SP98   

     AC  rain  sun  refill liters refill gas  
0     0     0    0           45.0        E10  
1     0     0    0            NaN        NaN  
2     0     0    0            NaN        NaN  
3     0     0    0            NaN        NaN  
4     0     0    0            NaN        NaN  
..   ..   ...  ...            ...        ...  
383   0     0    0            NaN        NaN  
384   1     0    0            NaN        NaN  
385   0     0    0            NaN        NaN  
386   1     0    0            NaN        NaN  
387   1     0    0            NaN        NaN  

[388 rows x 12 columns]

In [65]:
data["gas_type"].unique()

array(['E10', 'SP98'], dtype=object)

In [75]:
data["refill gas"].unique()

array(['E10', nan, 'SP98'], dtype=object)

In [84]:
data["refill liters"].value_counts(dropna=False)

NaN     375
45.0      2
37.7      2
39.0      2
37.6      1
38.0      1
38.3      1
10.0      1
41.0      1
37.0      1
37.2      1
Name: refill liters, dtype: int64

In [83]:
data["refill gas"].value_counts(dropna=False)

NaN     375
SP98      8
E10       5
Name: refill gas, dtype: int64

In [86]:
data["specials"].value_counts(dropna=False)

NaN                   295
rain                   32
sun                    27
AC                     14
AC Rain                10
AC Sun                  5
snow                    3
AC snow                 1
half rain half sun      1
Name: specials, dtype: int64

In [88]:
# Too many NaN values 
# droping "specials", "refill gas" and "refill liters"

In [90]:
columntodrop = ["specials","refill liters","refill gas"]
data.drop(columns=columntodrop, inplace=True)

In [92]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   distance      388 non-null    float64
 1   consume       388 non-null    float64
 2   speed         388 non-null    int64  
 3   temp_inside   376 non-null    float64
 4   temp_outside  388 non-null    int64  
 5   gas_type      388 non-null    object 
 6   AC            388 non-null    int64  
 7   rain          388 non-null    int64  
 8   sun           388 non-null    int64  
dtypes: float64(3), int64(5), object(1)
memory usage: 27.4+ KB


In [93]:
data.head()

distance  consume  speed  temp_inside  temp_outside gas_type  AC  rain  sun
0      28.0      5.0     26         21.5            12      E10   0     0    0
1      12.0      4.2     30         21.5            13      E10   0     0    0
2      11.2      5.5     38         21.5            15      E10   0     0    0
3      12.9      3.9     36         21.5            14      E10   0     0    0
4      18.5      4.5     46         21.5            15      E10   0     0    0

In [98]:
#Fill Missing Values in data["temp_inside"]
#data["temp_inside"] = data["temp_inside"].fillna(data["temp_inside"].mode())
data["temp_inside"] = data["temp_inside"].fillna(data["temp_inside"].mode()[0])

In [99]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   distance      388 non-null    float64
 1   consume       388 non-null    float64
 2   speed         388 non-null    int64  
 3   temp_inside   388 non-null    float64
 4   temp_outside  388 non-null    int64  
 5   gas_type      388 non-null    object 
 6   AC            388 non-null    int64  
 7   rain          388 non-null    int64  
 8   sun           388 non-null    int64  
dtypes: float64(3), int64(5), object(1)
memory usage: 27.4+ KB


In [102]:
#We are creating a new column
#data['gas_consumed']= (data['distance']/data['consume']) * 100
data['gas_consumed'] = (data['distance'] * data['consume']) / 100

In [103]:
data.head()

distance  consume  speed  temp_inside  temp_outside gas_type  AC  rain  \
0      28.0      5.0     26         21.5            12      E10   0     0   
1      12.0      4.2     30         21.5            13      E10   0     0   
2      11.2      5.5     38         21.5            15      E10   0     0   
3      12.9      3.9     36         21.5            14      E10   0     0   
4      18.5      4.5     46         21.5            15      E10   0     0   

   sun  gas_consumed  
0    0        1.4000  
1    0        0.5040  
2    0        0.6160  
3    0        0.5031  
4    0        0.8325

In [104]:
#Each row have the amount of gas consumed by Cobify's cars company

In [105]:
#Barcelona 
#SP98 = 1.759
#E10 = 1.439
#So for each row with E10 as gas_type we gonna compute the amount of money each trip cost, same for SP98 
# based on the amount of gas consumed.

In [106]:
#We create a new column that will display the amount of money to pay based on the gas_consumed and price of gas type

In [110]:
data['amount'] = np.where(data["gas_type"] == 'E10',data["gas_consumed"]*1.439,data["gas_consumed"]*1.759).round(2)

In [112]:
data.head()

distance  consume  speed  temp_inside  temp_outside gas_type  AC  rain  \
0      28.0      5.0     26         21.5            12      E10   0     0   
1      12.0      4.2     30         21.5            13      E10   0     0   
2      11.2      5.5     38         21.5            15      E10   0     0   
3      12.9      3.9     36         21.5            14      E10   0     0   
4      18.5      4.5     46         21.5            15      E10   0     0   

   sun  gas_consumed  amount  
0    0        1.4000    2.01  
1    0        0.5040    0.73  
2    0        0.6160    0.89  
3    0        0.5031    0.72  
4    0        0.8325    1.20

In [115]:
data["amount"].unique()

array([ 2.01,  0.73,  0.89,  0.72,  1.2 ,  0.76,  0.49,  0.88,  0.45,
        0.91,  1.  ,  0.78,  1.04,  1.81,  0.84,  1.27,  2.69,  0.87,
        1.83,  0.8 ,  2.  ,  1.21,  1.47,  1.51,  1.54,  1.45,  0.94,
        0.85,  0.99,  2.25,  1.18,  1.5 ,  0.52,  0.82,  1.15,  0.71,
        0.32,  0.77,  0.63,  0.31,  0.35,  1.38,  1.02,  2.26,  1.06,
        0.86,  1.41,  0.69, 13.23,  1.34,  0.92,  1.23,  0.4 ,  1.03,
        0.95,  1.17,  0.93,  1.13,  0.22,  1.25,  0.67,  1.35,  2.22,
        2.45,  0.41,  0.66,  1.14,  1.16,  1.37,  1.24,  1.22,  1.1 ,
        1.46,  1.29,  0.5 ,  0.38,  2.67,  1.65,  0.59,  2.13, 15.74,
        0.56,  0.98,  1.49,  1.93,  2.57,  0.54,  2.42,  1.32,  1.4 ,
        2.39,  0.51,  1.7 ,  1.59,  0.57,  0.44,  1.56,  2.48,  0.96,
        0.7 ,  0.26,  2.43,  2.55,  0.97,  1.52,  2.74,  3.04,  3.  ,
        1.84,  3.9 ,  3.13,  0.55,  1.08,  3.07,  2.27,  0.83,  1.85,
        4.05,  1.26,  2.15,  0.9 ,  3.71,  2.56,  5.14,  8.63,  4.16,
        3.61,  4.74,

In [117]:
data.to_csv('TechChallengeData.csv',index=False)